# XYkillJS 插件配置文件

# V3.2.1
# 修复一个错误

# 可使用指令： /rexykilljs 重新加载配置文件
# 为了保护服务器性能 将每5分钟保存一次每个玩家的每日上限数据
# 修复每次重启服务器/崩服每日上限重新统计的问题
# 注意请勿在深夜12点左右重启服务器 会影响到每日上限的重置！
#（如果遇到可以在关闭服务器的情况下清空MonsterSETlimit.yml文件夹再开服务器）

# 最小奖励金额
min: 8.0
# 最大奖励金额
max: 22.0
# 全局消息
message: "&a你击杀了怪物，获得了 &e{reward} &a小钱钱！"

# 怪物设置
MonsterSET:
  ZOMBIE:
    limit: 20000.0
    message: "&c你已经达到了僵尸的每日击杀奖励上限！"
  SKELETON:
    limit: 15000.0
    message: "&c你已经达到了骷髅的每日击杀奖励上限！"
  CREEPER:
    limit: 10000.0
    message: "&c你已经达到了苦力怕的每日击杀奖励上限！"
  PIG_ZOMBIE:
    limit: 30000.0
    message: "&c你已经达到了僵尸猪人的每日击杀奖励上限！"


# 怪物设置内可以按照格式无限添加怪物哦！

# 例如：
#  Super_Man:  #怪物英文id
#    limit: 10000.0  #每日击杀掉落金钱上限
#    message: "&c你已经达到了超人的每日击杀奖励上限！"  #到达上限的提示

# 注意不同版本的怪物英文id有所不同，请自行查阅更改！